Update nixpkgs and crane
nixpkgs update is to get latest redis and crane had to be updated
because otherwise we get:
```sh
> error: output file
/build/hw9n9iy0pniajp7hz9glfhjcxcvh9fvf-source/target/release/deps/libopenssl_sys-4a50bfca2de70625.rmeta
is not writeable -- check its permissions       >       > error: could
not compile `openssl-sys` (lib) due to previous error
```